AllCops:
  EnabledByDefault: true
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/ConstantResolution:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false